version: 3
endpoint: https://known-sunbeam-41.hasura.app
metadata_directory: metadata
admin_secret: 3f124uWkzlwitYxUIhBUUWi5W6dj0ZFFzcBa7neS2X44RapFa2Ey8XpiADUUufe3
actions:
  kind: synchronous
  handler_webhook_baseurl: https://absinthelabs-test.onrender.com
